// Generated by CoffeeScript 1.3.3
(function() {
  var http, io, port, server;

  http = require('http');

  port = parseInt(process.argv[2], 10);

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end('hello world');
  });

  server.listen(port);

  io = (require('socket.io')).listen(server);

  io.configure('production', function() {
    io.enable('browser client etag');
    io.set('log level', 1);
    return io.set('transports', ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']);
  });

  io.sockets.on('connection', function(socket) {
    console.log('connection ' + socket.id);
    return socket.on('disconnect', function() {
      return console.log('disconnection ' + socket.id);
    });
  });

  console.log('Server running at *:' + port);

}).call(this);
